version: "3"
services:
  ui:
   image: georgewilsonal/react-frontend-todo:1.0.1
   ports:
    -  3000:80
   container_name: mern-ui
   networks:
    -  mern-stack-net
   depends_on:
    - api
   stdin_open: true
   tty: true

  api:
   image: georgewilsonal/koa-rest:1.0.0
   ports:
     - 1337:1337
   container_name: mern-api
   networks:
     - mern-stack-net
   environment:
     - MONGO_CONNECTION_STRING=mongodb://db:27017/
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local

